/* eslint-disable no-unused-vars */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useState } from "react";
import {
  TextField,
  MenuItem,
  Select,
  Grid,
  FormControl,
  Box,
  Typography,
  Divider,
} from "@material-ui/core";
import { FaRocket } from "react-icons/fa";
import PostLoader from "./components/Posts";

/**
 * Home page
 * @returns {JSX.Element}: Element responsible for rendering the main page
 */
export enum FilterPossibilities {
  recent = "Mais Novas",
  older = "Mais Antigas",
  null = "null",
}

export interface IFilter {
  filter: FilterPossibilities;
}

export default function Home() {
  const [filter, setFilter] = useState<IFilter>({
    filter: FilterPossibilities.null,
  });
  const [search, setSearch] = useState<string>("");

  const handleChangeSearch = (event: any) => {
    setSearch(event.target.value);
  };

  const handleChange = (event: any) => {
    setFilter({ filter: event.target.value });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Space Flight News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/** Criar Navbar Space Flight News */}
        <Grid container spacing={2}>
          <Grid item xs={6}></Grid>
          <Grid item xs={3} className={styles.grid}>
            <TextField
              id="outlined-basic"
              label="Procurar"
              variant="outlined"
              onChange={handleChangeSearch}
            />
          </Grid>
          <Grid item xs={3} className={styles.grid}>
            <FormControl className={styles.filter}>
              <Select
                labelId="demo-simple-select-helper-label"
                id="demo-simple-select-helper"
                value={filter.filter}
                label={filter.filter}
                onChange={handleChange}
              >
                <MenuItem value={FilterPossibilities.recent}>
                  {FilterPossibilities.recent}
                </MenuItem>
                <MenuItem value={FilterPossibilities.older}>
                  {FilterPossibilities.older}
                </MenuItem>
              </Select>
            </FormControl>
          </Grid>
        </Grid>
        <Box className={styles.logo}>
          <Box className={styles.logo__container}>
            <FaRocket className={styles.logo__rocket}></FaRocket>
          </Box>
        </Box>
        <Typography variant="h3" style={{ textAlign: "center" }}>
          Space Flight News
        </Typography>
        <Divider style={{ marginTop: "4em" }}></Divider>
        <PostLoader search={search} order={filter}></PostLoader>
      </main>

      <footer></footer>
    </div>
  );
}
