name: Hourly cron job
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --location --request POST 'https://space-flight-news-seven.vercel.app//api/articles/populate'
